CREATE TABLE user_accounts (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE job_seeker_profiles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    full_name VARCHAR2(255),
    headline VARCHAR2(255),
    skills VARCHAR2(1000),
    location VARCHAR2(255),
    experience_summary CLOB,
    updated_at TIMESTAMP,
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES user_accounts(id)
);

CREATE TABLE job_poster_profiles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    company_name VARCHAR2(255),
    contact_name VARCHAR2(255),
    contact_title VARCHAR2(255),
    location VARCHAR2(255),
    updated_at TIMESTAMP,
    CONSTRAINT fk_poster_profiles_user FOREIGN KEY (user_id) REFERENCES user_accounts(id)
);

CREATE TABLE job_posts (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    poster_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    location VARCHAR2(255),
    skills VARCHAR2(1000),
    status VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_job_posts_user FOREIGN KEY (poster_id) REFERENCES user_accounts(id)
);

CREATE TABLE chat_messages (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    sender VARCHAR2(20) NOT NULL,
    message CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_messages_user FOREIGN KEY (user_id) REFERENCES user_accounts(id)
);

CREATE TABLE session_tokens (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    token VARCHAR2(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_session_tokens_user FOREIGN KEY (user_id) REFERENCES user_accounts(id)
);
