CREATE TABLE users (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(200)        NOT NULL,
    email         VARCHAR2(255) UNIQUE NOT NULL,
    country       VARCHAR2(80),
    hourly_rate   NUMBER(10,2),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
